apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: staype
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: staype-microservices-booking-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - secretRef:
                name: booking-env
          env:
            - name: PORT
              value: "8083"

            - name: REGISTRY_SERVER_URL
              value: "http://registry-service:8761"

            - name: BOOKING_MYSQL_HOST
              value: "booking-mysql"

            - name: BOOKING_MYSQL_PORT
              value: "3306"

            - name: BOOKING_MYSQL_USER
              value: "booking_user"

            - name: BOOKING_MYSQL_PASSWORD
              value: "booking_pass"

            - name: BOOKING_MYSQL_DATABASE
              value: "staype_booking_db"

            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:8082"

            - name: AUTH_SERVICE_URL
              value: "http://auth-service:8081"

            - name: GATEWAY_SECRET
              value: "staype-secret"

            - name: MAX_RESERVA_DAYS
              value: "365"

            - name: MAX_RESERVA_FUTURE_YEARS
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: staype
spec:
  selector:
    app: booking-service
  ports:
    - port: 8083
      targetPort: 8083