apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: staype
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: staype-microservices-catalog-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: catalog-env
                optional: true
          env:
            - name: PORT
              value: "8082"
            - name: SERVICE_NAME
              value: "catalog-service"
            - name: REGISTRY_SERVER_URL
              value: "http://registry-service:8761"
            - name: GATEWAY_SECRET
              value: "staype-secret"
            - name: DB_USER
              value: "sa"
            - name: DB_PASSWORD
              value: "Staype123!"
            - name: DB_SERVER
              value: "sqlserver"
            - name: DB_DATABASE
              value: "staype_catalog_db"
            - name: DB_PORT
              value: "1433"
            - name: DB_ENCRYPT
              value: "false"
            - name: DB_TRUST_SERVER_CERTIFICATE
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: staype
spec:
  selector:
    app: catalog-service
  ports:
    - port: 8082
      targetPort: 8082